import { createApp, type App } from 'vue'
import { createPinia, type Pinia } from 'pinia'
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate'

import AppComponent from './App.vue'
import router from './router'
import './assets/main.css'

// Font Awesome
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core'
import {
  faEnvelope,
  faLock,
  faEye,
  faEyeSlash,
  faUser,
  faCircleExclamation,
  faTriangleExclamation,
  faBars,
  faXmark,
  faSort,
  faSortUp,
  faSortDown,
  faHome,
  faCar,
  faCarSide,
  faMotorcycle,
  faIdCard,
  faFileContract,
  faGear,
  faSignOutAlt,
  faBell,
  faBellSlash,
  faSearch,
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  faArrowUp,
  faArrowDown,
  faCheckCircle,
  faExclamationCircle,
  faTimesCircle,
  faHistory,
  faUserCircle,
  faAddressBook,
  faEdit,
  faCheck,
  faCheckDouble,
  faTimes,
  faCamera,
  faArrowLeft,
  faArrowRight,
  faInfoCircle,
  faHeartbeat,
  faInbox,
  faUsers,
  faBuilding,
  faTrash,
  faClipboardList,
  faCalendar,
  faMapMarkerAlt,
  faCog,
  faCreditCard,
  faTrashAlt,
  faFilter,
  faTag,
  faFile,
  faFileAlt,
  faCalendarAlt,
  faClock,
  faInfo,
  faPrint,
  faMoneyBillWave,
  faDownload,
  faPalette,
  faCalendarCheck,
  faCalendarTimes,
  faTachometerAlt,
  faExclamationTriangle,
  faClipboard,
  faUpload,
  faQrcode,
  faPlus,
  faCogs,
  faSpinner,
  faQuestionCircle,
  faCircleInfo,
} from '@fortawesome/free-solid-svg-icons'
import { faGoogle } from '@fortawesome/free-brands-svg-icons'

// Add icons to the library
const icons: IconDefinition[] = [
  faEnvelope,
  faLock,
  faEye,
  faEyeSlash,
  faUser,
  faGoogle,
  faCircleExclamation,
  faTriangleExclamation,
  faBars,
  faUserCircle,
  faAddressBook,
  faEdit,
  faCheck,
  faCheckDouble,
  faTimes,
  faCamera,
  faArrowLeft,
  faArrowRight,
  faArrowDown,
  faInfoCircle,
  faHeartbeat,
  faInbox,
  faUsers,
  faBuilding,
  faMapMarkerAlt,
  faXmark,
  faHome,
  faCar,
  faCarSide,
  faMotorcycle,
  faIdCard,
  faFileContract,
  faGear,
  faSignOutAlt,
  faBell,
  faBellSlash,
  faSearch,
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  faArrowUp,
  faCheckCircle,
  faExclamationCircle,
  faTimesCircle,
  faHistory,
  faCog,
  faCreditCard,
  faTrashAlt,
  faFilter,
  faSort,
  faSortUp,
  faSortDown,
  faTrash,
  faTag,
  faFile,
  faFileAlt,
  faCalendar,
  faCalendarAlt,
  faClock,
  faInfo,
  faPrint,
  faClipboardList,
  faMoneyBillWave,
  faDownload,
  faPalette,
  faCalendarCheck,
  faCalendarTimes,
  faTachometerAlt,
  faExclamationTriangle,
  faClipboard,
  faUpload,
  faQrcode,
  faPlus,
  faCogs,
  faSpinner,
  faQuestionCircle,
  faCircleInfo,
]
library.add(...icons)

const app: App = createApp(AppComponent)
const pinia: Pinia = createPinia()
pinia.use(piniaPluginPersistedstate)

app.use(pinia)
app.use(router)
app.component('font-awesome-icon', FontAwesomeIcon)

app.mount('#app')
